### ISSUE TITLE
add more options

### ISSUE THREAD

**Issue by datfooldive** [idhyt/AndroidFridaFuzz#1]
its will nice if you add `frida.get_remote_device()` for frida-gadget and frida-server

because i use frida in termux so `frida.get_usb_device()` not work

**Comment by idhyt** [comment]
overwrite [attach](https://github.com/idhyt/AndroidFridaFuzz/blob/master/andff/implement/frida.py#L26) function to fit your environment 🤪

This is an experimental demo, in actual use, U can modify it (mutator or seed serialize)to work better 🥸
